name: Auto label
on:
  issues:
    types: ['opened']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2.1.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-comments: true
          labels-synonyms: '{"gssoc23":["gssoc","GSSoC23","gssoc23","GSSOC","Gssoc23"]}'
