name: Example

on:
  schedule:
    - cron: '12 22 * * *' # Runs at 22:12 UTC every day

jobs:
  # Best used in combination with actions/stale to assign a Stale label
  
  unassign-issues-labeled-waiting-for-contributor-after-7-days-of-inactivity:
    name: Unassign issues labeled "Wartet auf Contributor" after 7 days of inactivity.
    runs-on: ubuntu-latest
    steps:
      - uses: boundfoxstudios/action-unassign-contributor-after-days-of-inactivity@main
        with:
          last-activity: 7 # After how many days the issue should get unassigned
          labels: 'Stale' # Only search for issues containing this labels (comma-separated)
          exempt-assignees: 'Octo,Cat' # Exempt some assignees from being unassigned
          labels-to-remove: 'Stale' # Labels to remove after unassigning an issue
          message: 'Automatically unassigned after 7 days of inactivity.'
